name: Pre-commit Checks

permissions:
  contents: read

on:
  push:
    branches: ["main", "master", "dev"]
  pull_request:
    branches: ["main", "master", "dev"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
